# Limpieza de datos con python

**Pasos para instalar kaggle**

-  pip install kaggle / conda install -c conda-forge kaggle
- Ir a su perfil de Kaggle, buscar la seccion de API 
- Legacy API Credentials
- Se descargar un archivo, ponerlo en la carptea  C:\Users\user\.kaggle (si no exites crea la carpeta con mkdir .kaggle)
- kaggle competitions list #Con esto checar las intalacion 
- Busca en kaggle un dataset que te guste

In [4]:
import kaggle
kaggle.api.dataset_download_files('ariyoomotade/netflix-data-cleaning-analysis-and-visualization', path='.', unzip=True)

Dataset URL: https://www.kaggle.com/datasets/ariyoomotade/netflix-data-cleaning-analysis-and-visualization

In [9]:
# pip install pandas
# pip install matplotlib

import pandas as pd
import matplotlib.pyplot as plt

In [8]:
# Leyenbdo nuestro dataframe
df = pd.read_csv("netflix1.csv")

In [10]:
df.head()      # primeras filas

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,PG-13,90 min,Documentaries
1,s3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,TV-PG,91 min,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies"

In [11]:
df.tail()      # últimas filas

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
8785,s8797,TV Show,Yunus Emre,Not Given,Turkey,1/17/2017,2016,TV-PG,2 Seasons,"International TV Shows, TV Dramas"
8786,s8798,TV Show,Zak Storm,Not Given,United States,9/13/2018,2016,TV-Y7,3 Seasons,Kids' TV
8787,s8801,TV Show,Zindagi Gulzar Hai,Not Given,Pakistan,12/15/2016,2012,TV-PG,1 Season,"International TV Shows, Romantic TV Shows, TV ..."
8788,s8784,TV Show,Yoko,Not Given,Pakistan,6/23/2018,2016,TV-Y,1 Season,Kids' TV
8789,s8786,TV Show,YOM,Not Given,Pakistan,6/7/2018,2016,TV-Y7,1 Season,Kids' TV

In [12]:
df.info()      # tipos de datos

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8790 entries, 0 to 8789
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8790 non-null   object
 1   type          8790 non-null   object
 2   title         8790 non-null   object
 3   director      8790 non-null   object
 4   country       8790 non-null   object
 5   date_added    8790 non-null   object
 6   release_year  8790 non-null   int64
 7   rating        8790 non-null   object
 8   duration      8790 non-null   object
 9   listed_in     8790 non-null   object
dtypes: int64(1), object(9)
memory usage: 686.8+ KB

In [13]:
df.describe()  # estadísticas

       release_year
count   8790.000000
mean    2014.183163
std        8.825466
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

In [14]:
df.describe(include='all')

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
count,8790,8790,8790,8790,8790,8790,8790.000000,8790,8790,8790
unique,8790,2,8787,4528,86,1713,NaN,14,220,513
top,s8786,Movie,9-Feb,Not Given,United States,1/1/2020,NaN,TV-MA,1 Season,"Dramas, International Movies"
freq,1,6126,2,2588,3240,110,NaN,3205,1791,362
mean,NaN,NaN,NaN,NaN,NaN,NaN,2014.183163,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,8.825466,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,1925.000000,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,2013.000000,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,2017.000000,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,2019.000000,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,2021.000000,NaN,NaN,NaN

In [18]:
# pip install pygwalker    / conda install -c conda-forge pygwalker
import pygwalker as pyg
pyg.walk(df)

Box(children=(HTML(value='\n<div id="ifr-pyg-00064b890197562fCWsToJulYmdyGcFE" style="height: auto">\n    <hea…

## Chequeo nuestros datos

In [25]:
df.shape #Muestra las dimensiones del dataset (número de filas y columnas).

(8790, 10)

In [ ]:
df.isna().sum().sort_values(ascending=False).head(10) #Cuenta los valores faltantes (NaN) por columna, los ordena de mayor a menor y muestra las 10 columnas con más datos faltantes.

show_id         0
type            0
title           0
director        0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
dtype: int64

In [27]:
df['type'].value_counts() #Cuenta cuántas veces aparece cada categoría en la columna type

type
Movie      6126
TV Show    2664
Name: count, dtype: int64

In [26]:
df['rating'].value_counts().head(15)  #Cuenta la frecuencia de cada clasificación de contenido (rating) y muestra las 15 más comunes.

rating
TV-MA       3205
TV-14       2157
TV-PG        861
R            799
PG-13        490
TV-Y7        333
TV-Y         306
PG           287
TV-G         220
NR            79
G             41
TV-Y7-FV       6
NC-17          3
UR             3
Name: count, dtype: int64

# Limpieza

In [34]:
df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce') # Convierte la columna date_added a formato de fecha (datetime). Si algún valor no se puede convertir, 
#                                                                           lo reemplaza por NaN en lugar de generar un error.
print(df['date_added'])

0      2021-09-25
1      2021-09-24
2      2021-09-24
3      2021-09-22
4      2021-09-24
          ...
8785   2017-01-17
8786   2018-09-13
8787   2016-12-15
8788   2018-06-23
8789   2018-06-07
Name: date_added, Length: 8790, dtype: datetime64[ns]

In [36]:
df['added_year'] = df['date_added'].dt.year  #Crea una nueva columna con el año en que se añadió el contenido.
df['added_year'] = df['date_added'].dt.year
df['added_month'] = df['date_added'].dt.month
df['added_month_name'] = df['date_added'].dt.month_name()

# Limpiemos otra columna

In [39]:
df = df.replace("Not Given", pd.NA)

In [40]:
df['duration_num'] = df['duration'].str.extract(r'(\d+)').astype('float')
print(df['duration_num'])

0        90.0
1         1.0
2         1.0
3        91.0
4       125.0
        ...
8785      2.0
8786      3.0
8787      1.0
8788      1.0
8789      1.0
Name: duration_num, Length: 8790, dtype: float64

In [41]:
# unidad (min / Season(s))
df['duration_unit'] = df['duration'].str.extract(r'([A-Za-z]+)')
print(df['duration_unit'])

0           min
1        Season
2        Season
3           min
4           min
         ...
8785    Seasons
8786    Seasons
8787     Season
8788     Season
8789     Season
Name: duration_unit, Length: 8790, dtype: object

In [42]:
pyg.walk(df)

Box(children=(HTML(value='\n<div id="ifr-pyg-00064b8aabaef354uD8mzRPEpt4xoZhO" style="height: auto">\n    <hea…